#include "StyleBrowserFontAwesomeGlyphs.h"

#include "EditorFontGlyphs.h"

#define ADD_MAP_ELEMENT(ElementName) {TEXT("FEditorFontGlyphs::" #ElementName), FEditorFontGlyphs::ElementName }

// From FEditorFontGlyphs 
const TMap<FString, FText> FStyleBrowserFontAwesomeGlyphs::EditorGlyphsMap =
{
	ADD_MAP_ELEMENT(Angle_Double_Left),
	ADD_MAP_ELEMENT(Angle_Double_Right),
	ADD_MAP_ELEMENT(Angle_Left),
	ADD_MAP_ELEMENT(Angle_Right),
	ADD_MAP_ELEMENT(Angle_Up),
	ADD_MAP_ELEMENT(Archive),
	ADD_MAP_ELEMENT(Arrow_Circle_O_Right),
	ADD_MAP_ELEMENT(Arrow_Left),
	ADD_MAP_ELEMENT(Arrow_Right),
	ADD_MAP_ELEMENT(Arrows),
	ADD_MAP_ELEMENT(Ban),
	ADD_MAP_ELEMENT(Bars),
	ADD_MAP_ELEMENT(Book),
	ADD_MAP_ELEMENT(Bug),
	ADD_MAP_ELEMENT(Car),
	ADD_MAP_ELEMENT(Caret_Down),
	ADD_MAP_ELEMENT(Caret_Right),
	ADD_MAP_ELEMENT(Caret_Square_O_Down),
	ADD_MAP_ELEMENT(Caret_Square_O_Left),
	ADD_MAP_ELEMENT(Caret_Square_O_Right),
	ADD_MAP_ELEMENT(Caret_Square_O_Up),
	ADD_MAP_ELEMENT(Caret_Up),
	ADD_MAP_ELEMENT(Check),
	ADD_MAP_ELEMENT(Check_Circle),
	ADD_MAP_ELEMENT(Circle),
	ADD_MAP_ELEMENT(Circle_O),
	ADD_MAP_ELEMENT(Clock_O),
	ADD_MAP_ELEMENT(Cog),
	ADD_MAP_ELEMENT(Cogs),
	ADD_MAP_ELEMENT(Crosshairs),
	ADD_MAP_ELEMENT(Database),
	ADD_MAP_ELEMENT(Download),
	ADD_MAP_ELEMENT(Eraser),
	ADD_MAP_ELEMENT(Exchange),
	ADD_MAP_ELEMENT(Exclamation),
	ADD_MAP_ELEMENT(Exclamation_Triangle),
	ADD_MAP_ELEMENT(Expand),
	ADD_MAP_ELEMENT(External_Link),
	ADD_MAP_ELEMENT(Eye),
	ADD_MAP_ELEMENT(Eye_Slash),
	ADD_MAP_ELEMENT(Fast_Forward),
	ADD_MAP_ELEMENT(File),
	ADD_MAP_ELEMENT(Film),
	ADD_MAP_ELEMENT(Filter),
	ADD_MAP_ELEMENT(Floppy_O),
	ADD_MAP_ELEMENT(Folder),
	ADD_MAP_ELEMENT(Folder_Open),
	ADD_MAP_ELEMENT(Hourglass),
	ADD_MAP_ELEMENT(Hourglass_O),
	ADD_MAP_ELEMENT(Info),
	ADD_MAP_ELEMENT(Info_Circle),
	ADD_MAP_ELEMENT(Level_Down),
	ADD_MAP_ELEMENT(Level_Up),
	ADD_MAP_ELEMENT(Lightbulb_O),
	ADD_MAP_ELEMENT(Line_Chart),
	ADD_MAP_ELEMENT(Link),
	ADD_MAP_ELEMENT(Lock),
	ADD_MAP_ELEMENT(Long_Arrow_Down),
	ADD_MAP_ELEMENT(Long_Arrow_Right),
	ADD_MAP_ELEMENT(Map),
	ADD_MAP_ELEMENT(Map_Marker),
	ADD_MAP_ELEMENT(Minus),
	ADD_MAP_ELEMENT(Minus_Circle),
	ADD_MAP_ELEMENT(Paper_Plane),
	ADD_MAP_ELEMENT(Pause),
	ADD_MAP_ELEMENT(Pause_Circle),
	ADD_MAP_ELEMENT(Pencil),
	ADD_MAP_ELEMENT(Pencil_Square),
	ADD_MAP_ELEMENT(Play),
	ADD_MAP_ELEMENT(Play_Circle),
	ADD_MAP_ELEMENT(Plug),
	ADD_MAP_ELEMENT(Plus),
	ADD_MAP_ELEMENT(Plus_Circle),
	ADD_MAP_ELEMENT(Question),
	ADD_MAP_ELEMENT(Random),
	ADD_MAP_ELEMENT(Recycle),
	ADD_MAP_ELEMENT(Refresh),
	ADD_MAP_ELEMENT(Share),
	ADD_MAP_ELEMENT(Share_Alt),
	ADD_MAP_ELEMENT(Sign_In),
	ADD_MAP_ELEMENT(Sign_Out),
	ADD_MAP_ELEMENT(Square),
	ADD_MAP_ELEMENT(Star),
	ADD_MAP_ELEMENT(Step_Forward),
	ADD_MAP_ELEMENT(Stop),
	ADD_MAP_ELEMENT(Terminal),
	ADD_MAP_ELEMENT(Th),
	ADD_MAP_ELEMENT(Thumb_Tack),
	ADD_MAP_ELEMENT(Times),
	ADD_MAP_ELEMENT(Times_Circle),
	ADD_MAP_ELEMENT(Trash),
	ADD_MAP_ELEMENT(Undo),
	ADD_MAP_ELEMENT(Unlock),
	ADD_MAP_ELEMENT(Video_Camera)
};

#undef ADD_MAP_ELEMENT
